# Generated by Django 2.2 on 2020-09-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('city', models.CharField(max_length=64, verbose_name='город')),
                ('email', models.CharField(max_length=64, verbose_name='email')),
                ('phone', models.CharField(max_length=64, verbose_name='телефон')),
                ('adress', models.CharField(blank=True, max_length=128, verbose_name='адрес')),
            ],
        ),
    ]
