# Generated by Django 2.2 on 2020-10-27 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20201026_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='locale',
            field=models.CharField(blank=True, max_length=2, verbose_name='язык'),
        ),
        migrations.AddField(
            model_name='shopuserprofile',
            name='profile',
            field=models.CharField(blank=True, max_length=512, verbose_name='адрес профиля'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 29, 19, 27, 15, 805996, tzinfo=utc)),
        ),
    ]
